### ISSUE TITLE
how to Get Selected Values instead of indexes

### ISSUE THREAD

**Issue by rockstarvibu** [hugocastelani/drag_select_grid_view#16] opened 2020-09-17 21:56 UTC
Hey I'm able to get Selected index by calling controller.value. but instead of indexes I want the values which the user selected.. how to do that...
Thanks

**Comment by rockstarvibu** [comment] 2020-09-22 16:03
reply

**Comment by hugocastelani** [comment] 2020-09-22 23:55
`DragSelectGridView` cannot provide you such information because it doesn't link any data to any index. In fact, the indexes are used by the library users to decide which widget to build in `DragSelectGridView.itemBuilder`, not by the library itself. 

As this issue doesn't concern the library, I'm closing it. However, I believe I should be able to help you with your problem if you give me more details about what are you trying to do. Some code would also help.

**Closed by hugocastelani** 2020-09-22 23:55 UTC

**Comment by rockstarvibu** [comment] 2020-09-24 09:36
Hwy i just want to get the selected values in list...
For eg... User selected 5 items and when he clicks on FAB button then on next screen selected values should come instead of index. Can u help me with this?

Thanks

**Comment by rockstarvibu** [comment] 2020-09-25 20:20
?

**Comment by hugocastelani** [comment] 2020-09-25 23:03
I'm guessing you have access to the list with your values, so you could do something like:

```dart
final selectedValues = controller.value.selectedIndexes.map((index) => myValues[index]);
```

If this doesn't help you, I'll need some minimal piece of reproducible code to get a better understanding of your situation.
